name: flu_design
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  # ---- Core language ----
  - python=3.11.13

  # ---- Bioinformatics tools ----
  - mafft=7.505           # Multiple sequence alignment
  - iqtree=2.2.6          # Phylogenetic inference and model testing
  - cd-hit=4.7            # Clustering of sequences at 99% identity
  - seqkit=2.10.1         # FASTA/FASTQ manipulation and filtering

  # ---- Python scientific stack ----
  - biopython=1.83        # FASTA parsing and sequence utilities
  - pandas=2.3.3          # Data handling and tabular summaries
  - numpy=2.0.1           # Matrix operations and numerical analysis
  - matplotlib=3.10.7     # Plotting and figure generation
  - seaborn=0.13.2        # High-level statistical visualization
  - scipy=1.16.2          # Entropy, distance, and stats calculations
  - logomaker=0.8.7       # Sequence logo visualization
  - tqdm=4.67.1           # Progress bars for long computations

  # ---- Utility ----
  - pip                   # For installing any additional Python packages
